method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  batch_size:
    values:
      - 48
      - 64
  epochs:
    value: 100
  learning_rate:
    distribution: uniform
    max: 0.1
    min: 1e-06
  mode:
    value: img
  n_bands:
    value: 13
  n_classes:
    value: 9
  optimizer:
    values:
      - adam
      - sgd
      - adamW
  resolution:
    values:
      - 10
      - 20
  scheduler:
    values:
      - plateau
      - steplr
      - cosine
  use_mf:
    values:
      - true
      - false
  use_residual:
    values:
      - true
      - false
program: train.py
