project: M3F-Net
name: wandb_sweep
program: train.py

method: bayes
metric:
  goal: maximize
  name: test_r2
parameters:
  batch_size:
    values:
      - 48
      - 64
  epochs:
    value: 100
  learning_rate:
    distribution: uniform
    max: 0.1
    min: 1e-05
  mode:
    value: img
  n_bands:
    value: 13
  n_classes:
    value: 9
  optimizer:
    values:
      - adam
      - sgd
      - adamW
  resolution:
    values:
      - 10
      - 20
  scheduler:
    values:
      - plateau
      - steplr
      - cosine
  use_mf:
    values:
      - true
      - false
  use_residual:
    values:
      - true
      - false
  data_dir:
    value: './data'
  save_dir:
    value: './logs/sweep_results'
  transforms:
    values:
      - true
      - false
  gpus:
    value: 4

command:
  - ${env}
  - python
  - sweep_tune.py